services:
  - type: web
    name: xeno-shopify-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: xeno-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://xeno-shopify-frontend.onrender.com

  - type: web
    name: xeno-shopify-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://xeno-shopify-backend.onrender.com

databases:
  - name: xeno-db
    plan: free
